# Generated by Django 5.0.6 on 2024-06-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteller_reg',
            fields=[
                ('hstlr_id', models.AutoField(primary_key=True, serialize=False)),
                ('hstlr_fname', models.CharField(max_length=20)),
                ('hstlr_lname', models.CharField(max_length=20)),
                ('hstlr_email', models.EmailField(max_length=254, unique=True)),
                ('hstlr_phn', models.BigIntegerField()),
                ('admission_date', models.DateField()),
                ('hstlr_address', models.CharField(max_length=200)),
                ('f_name', models.CharField(max_length=40)),
                ('f_phn', models.BigIntegerField()),
                ('hstlr_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=3)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=5)),
                ('hstlr_passwd', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Hosteller Admission',
                'verbose_name_plural': 'Hosteller Admission',
            },
        ),
        migrations.CreateModel(
            name='Hstlin_reg',
            fields=[
                ('incharge_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phn', models.BigIntegerField()),
                ('admission_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=3)),
                ('passwd', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Hostel Incharge Admission',
                'verbose_name_plural': 'Hostel Incharge Admission',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('is_vacant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel1.hosteller_reg')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('hosteller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel1.hosteller_reg')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(auto_now_add=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostellers', to='hostel1.hosteller_reg')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel1.room')),
            ],
        ),
    ]
