# Generated by Django 5.0.6 on 2024-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel1.hosteller_reg')),
            ],
        ),
    ]
