# Generated by Django 5.0.6 on 2024-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0002_roomrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomallocation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='hosteller',
        ),
        migrations.RemoveField(
            model_name='roomrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='assigned_room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomrequest',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomAllocation',
        ),
    ]
