# Generated by Django 5.0.6 on 2024-06-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrequest',
            name='room_number',
        ),
    ]
