# Generated by Django 5.0.6 on 2024-06-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0005_remove_roomrequest_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
