# Generated by Django 5.0.6 on 2024-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0006_room_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteller_reg',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
