# Generated by Django 5.0.6 on 2024-07-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0008_alter_attendance_date_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='hosteller_reg',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('Other', 'other branch')], max_length=5),
        ),
    ]
