# Generated by Django 5.0.6 on 2024-07-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0009_alter_attendance_status_alter_hosteller_reg_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room', 'Room'), ('hostel', 'Hostel')], max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('response', models.TextField(blank=True, null=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel1.hosteller_reg')),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge', to='hostel1.hstlin_reg')),
            ],
        ),
    ]
