# Generated by Django 5.0.6 on 2024-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel1', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.CharField(default='HM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('room', 'Room'), ('mess', 'Mess'), ('washrooms', 'Washrooms'), ('other issues', 'Other Issues')], max_length=30),
        ),
    ]
